### PR TITLE
fix: Crash when pinging URL with 500 response

### LINKED ISSUE #227: App crashes when pinging fails due to HTTP 50X response
This happened whilst the gateway app was running in the background, though I don't think that'd make any difference.

```
    --------- beginning of crash
2020-12-17 11:22:25.676 13000-13039/tech.relaycorp.gateway E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: tech.relaycorp.gateway, PID: 13000
    io.ktor.client.features.ServerResponseException: Server error(https://poweb-frankfurt.relaycorp.cloud/: 502 Bad Gateway.
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:36)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:10)
        at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:96)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(Unknown Source:14)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:80)
        at tech.relaycorp.gateway.background.PingRemoteServer.pingURL(PingRemoteServer.kt:74)
        at tech.relaycorp.gateway.background.PingRemoteServer$pingURL$1.invokeSuspend(Unknown Source:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-12-17 11:22:25.737 765-780/? I/ActivityManager: Showing crash dialog for package tech.relaycorp.gateway u0
```

### PR DESCRIPTION
**Pull request by sdsantos**
Closes #227

### CODE REVIEW

File: app/src/main/java/tech/relaycorp/gateway/background/CheckInternetAccess.kt [hunk 1]
```diff
@@ -10,6 +10,6 @@ class CheckInternetAccess
         pingRemoteServer.pingURL(INTERNET_TEST_WEBSITE)
 
     companion object {
-        private const val INTERNET_TEST_WEBSITE = "https://google.com"
+        private const val INTERNET_TEST_WEBSITE = "https://httpstat.us/500"
```
Comment (gnarea) [inline app/src/main/java/tech/relaycorp/gateway/background/CheckInternetAccess.kt:13]: Presumably this is the change you made to test this but it isn't needed in the PR?

**Review by gnarea — CHANGES_REQUESTED** [review]

File: app/src/main/java/tech/relaycorp/gateway/background/CheckInternetAccess.kt (hunk 1 above)
Comment (sdsantos) [reply app/src/main/java/tech/relaycorp/gateway/background/CheckInternetAccess.kt:13]: Sorry, didn't looked at the diff. Just pushed forced a new version.

**Review by gnarea — APPROVED** [review]
