### PR TITLE
fix: Remote pings leak

### LINKED ISSUE #184: Internet and Public Gateway pings are leaking connections
After a while with the Gateway app opened, warnings start appearing stating:

```
OkHttpClient: A connection to https://poweb-test.relaycorp.tech/ was leaked. Did you forget to close a response body?
OkHttpClient: A connection to https://google.com/ was leaked. Did you forget to close a response body?
```

We need to fix the code making the ping calls so connections are properly closed.

### PR DESCRIPTION
**Pull request by sdsantos**
Closes #184

### CODE REVIEW

File: app/src/main/java/tech/relaycorp/gateway/background/PingRemoteServer.kt [hunk 1]
```diff
@@ -1,55 +1,40 @@
...
-                false
-            } catch (ex: Exception) {
-                logger.log(Level.INFO, "Could not reach $address:$port", ex)
-                false
-            } finally {
-                socket.close()
-            }
+
+    private val ktorClient by lazy {
+        HttpClient(Android)
```
Comment (gnarea) [inline app/src/main/java/tech/relaycorp/gateway/background/PingRemoteServer.kt:18]: Can you please add the user agent? `Relaynet Private Gateway/<version> (Android)`. Or it isn't easy to get the version of the app, just `Relaynet Private Gateway (Android)`.

That'd be helpful when I'm looking at the server logs.

**Review by gnarea — CHANGES_REQUESTED** [review]
