### PR TITLE
fix: Skip expired parcels

### LINKED ISSUE #128: Cargo generated for couriers may contain expired parcels
The following check uncovered this bug:

https://github.com/relaycorp/relaynet-gateway-android/blob/3850b9d2a0849b01070d0b65700ac40cdbebfce3/app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCargo.kt#L89-L93

I think we should change the following:

- Alter the SQL to skip expired parcels and parcel collection acknowledgements. They're purged periodically anyway.
- Replace the exception with a warning. Even if the condition is met due to a future regression, it shouldn't abort the delivery of the cargo. The worst that could happen is that the courier will get an expired cargo, in which case the courier will ACK it but it'll ignore it.

### PR DESCRIPTION
**Pull request by sdsantos**
Closes #128

### CODE REVIEW

File: app/src/main/java/tech/relaycorp/gateway/data/database/StoredParcelDao.kt [hunk 1]
```diff
@@ -27,22 +29,28 @@ interface StoredParcelDao {
     @Query(
         """
         SELECT * FROM Parcel
-        WHERE recipientLocation = :recipientLocation 
+        WHERE recipientLocation = :recipientLocation AND expirationTimeUtc > :expiresSince
```
Comment (gnarea) [inline app/src/main/java/tech/relaycorp/gateway/data/database/StoredParcelDao.kt:32]: How about we use `date('now')` instead of `:expiresSince`? That parameter isn't currently used by the code calling this method, and it probably shouldn't be set anyway.

According to the SQLite docs, `date('now')` uses UTC: https://www.sqlite.org/lang_datefunc.html

This comment also applies to `listForRecipients`.

**Review by gnarea — CHANGES_REQUESTED** [review]

File: app/src/main/java/tech/relaycorp/gateway/data/database/StoredParcelDao.kt (hunk 1 above)
Comment (sdsantos) [reply app/src/main/java/tech/relaycorp/gateway/data/database/StoredParcelDao.kt:32]: We're comparing against epoch milliseconds, so from what I could test on sqlite we would need to compare with something like `datetime(expirationTimeUtc / 1000, 'unixepoch' 'utc') > datetime('now', 'utc')` I believe.

I thought about that. But the fact that we're storing in epoch milliseconds is specified in the kotlin side, on the Converters. So I though I shouldn't be leaking that abstraction to SQL and then locking it there too.

Comment (gnarea) [reply app/src/main/java/tech/relaycorp/gateway/data/database/StoredParcelDao.kt:32]: I see. I didn't remember SQLite doesn't have proper data types for dates! Let's leave it as it is in that case.

**Comment by sdsantos** [comment]
@gnarea rebased, needs a new review ;)

**Review by gnarea — APPROVED** [review]
