### PR TITLE
fix: CCA with creation time 5 minutes before

### LINKED ISSUE #204: CCA generation doesn't account for clock drift
So if the courier app is even a second behind the android gw, the CCA will be refused.

We avoid this issue when generating cargo by setting the cargo's creation time to 5 mins ago.

Note we need to be careful not to introduce the same bug in https://github.com/relaycorp/relaynet-gateway-android/issues/205 when we fix this issue.

### PR DESCRIPTION
**Pull request by sdsantos**
Closes #204

### CODE REVIEW

**Review by gnarea — CHANGES_REQUESTED** [review]
This code duplicates #216 so I'd suggest to have a single implementation of the `calculateCreationDate()` function (e.g., `calculateCRCMessageCreationDate()`).

A CRC (Cargo Relay Connection) message is any message exchanged between gateways via couriers. Right now there's only CCAs and cargoes, but there could be more in the future.

File: app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt [hunk 1]
```diff
@@ -9,14 +9,16 @@ import kotlin.time.days
...
+    private val calculateCreationDate: CalculateCRCMessageCreationDate
 ) {
 
     suspend fun generate() =
         CargoCollectionAuthorization(
             recipientAddress = publicGatewayPreferences.getCogRPCAddress(),
             payload = "".toByteArray(),
             senderCertificate = localConfig.getCertificate(),
+            creationDate = calculateCreationDate.calculate(),
             ttl = TTL.inSeconds.toInt()
```
Comment (gnarea) [inline app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt:22]: I missed this in the first version of this PR: The TTL should be relative to the `creationDate`, which is going to be particularly important with this PR since the creation date could be the start date of the cert.

We solved this in the cargo generation by using `Duration.between()`, so we should probably factor that out like you've done with `CalculateCRCMessageCreationDate` -- perhaps re-purposing that class to add a second method like `calculateTTL()`.

**Review by gnarea — CHANGES_REQUESTED** [review]

File: app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt (hunk 1 above)
Comment (sdsantos) [reply app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt:22]: But it would be 5 minutes ago or sooner, while the TTL is 14 days. It won't matter much would it?

Comment (gnarea) [reply app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt:22]: You're right that with the current version of the code it won't make any difference. However, I'm planning to make a change at some point before the stable release that could make a difference:

I'm planning to change all the dates on cargoes and CCAs so that they're totally inaccurate, and this way an eavesdropper couldn't infer at what time the user and the courier met. The meeting time could be used to infer location. For this reason, the plan is to set the creation date to a random number of days in the past. I haven't yet figured out how big to make this range.

Comment (sdsantos) [reply app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt:22]: Then the TTL should also have some randomness to it I imagine. But I can make the TTL calculated for now as well.

Comment (gnarea) [reply app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt:22]: Good point! Yeah, the TTL should be the sum of the random duration in the past + the actual TTL. So this future change will be more elaborate than I thought anyway, so let's leave this as it is.

**Review by gnarea — APPROVED** [review]
