### PR TITLE
fix: Update CertificateStore to use scope

### LINKED ISSUE #570: Avoid storing the public gateway's identity certificate
Private gateways don't need the identity certificate of their public peer, but we're still storing as a "leftover" from the days when we used to encrypt cargo with that certificate (before integrating the Channel Session Protocol).

The only thing we need from that certificate is its public key, so that we can:

- Issue Cargo Delivery Authorisations (CDAs)
- Compute the public gateway's private address

### PR DESCRIPTION
**Pull request by sdsantos**
Related with #571 
Closes #570

### CODE REVIEW

File: app/src/main/java/tech/relaycorp/gateway/data/preference/PublicGatewayPreferences.kt [hunk 1]
```diff
@@ -56,6 +58,7 @@ class PublicGatewayPreferences
 
     suspend fun setCertificate(value: Certificate) {
         certificate.setAndCommit(Base64.encodeToString(value.serialize(), Base64.DEFAULT))
```
Comment (gnarea) [inline app/src/main/java/tech/relaycorp/gateway/data/preference/PublicGatewayPreferences.kt:60]: I think it'd be best not to stop the certificate any more now that we're integrating this change. Instead of storing the certificate, I think we should only store its `subjectPrivateAddress`.

The original version of this app stored the public gateway's certificate because that was also used for encryption. However, now that the Channel Session Protocol is integrated, private gateways need not store their public gateways' certificates.

(The public gateway will always include its certificate when registering a private gateway, but that's mainly so that the private gateway can log or store specific elements of the certificate, and so that the private gateway can verify that its new certificate was issued by the public gateway)

**Review by gnarea — CHANGES_REQUESTED** [review]

**Review by gnarea — DISMISSED** [review]
Nice one. Thanks!

**Review by gnarea — DISMISSED** [review]

**Review by gnarea — APPROVED** [review]
